version: "3.9"
services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379" # Puerto para Redis
      - "8001:8001" # Puerto para RedisInsight (interfaz gráfica)
    volumes:
      - redis-data:/data # Volumen para datos persistentes
    restart: "on-failure" # Reinicia si el contenedor falla

  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432" # Puerto para PostgreSQL
    volumes:
      - postgres-data:/var/lib/postgresql/data # Volumen para persistencia
    restart: "on-failure" # Reinicia si el contenedor falla

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80" # Puerto para acceder a pgAdmin
    depends_on:
      - postgres # Espera a que PostgreSQL esté disponible
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: "on-failure" # Reinicia si el contenedor falla

volumes:
  redis-data: # Volumen para Redis
  postgres-data: # Volumen para PostgreSQL
  pgadmin-data: # Volumen para pgAdmin