name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Tag Docker Images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-angular ./Frontend/Angular
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-express ./Backend/Backend-Express
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-flask ./Backend/Backend-Flask

      - name: Push Docker Images to DockerHub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend-angular
          docker push ${{ secrets.DOCKER_USERNAME }}/backend-express
          docker push ${{ secrets.DOCKER_USERNAME }}/backend-flask