name: End-to-End Tests

on:
  push:
    branches:
      - main

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          cd Frontend/Angular
          npm install

      - name: Run Cypress tests
        run: |
          cd Frontend/Angular
          npm run cypress:run