name: Kubernetes Deploy (Template)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      KUBECONFIG: ${{ secrets.KUBECONFIG }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      SERVICES: |
        Frontend/Angular=dummy-frontend
        Backend/Backend-Express=dummy-backend-express
        Backend/Backend-Flask=dummy-backend-flask

    steps:
      # Paso 1: Clonar el repositorio
      - name: Clonar el código
        uses: actions/checkout@v4

      # Paso 2: Instalar kubectl
      - name: Configurar kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: "latest"

      # Paso 3: Configurar Kubeconfig
      - name: Configurar Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "$KUBECONFIG" > ~/.kube/config
          echo "Kubeconfig configurado correctamente."

      # Paso 4: Iniciar sesión en DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      # Paso 5: Construir imágenes Docker
      - name: Build Docker Images
        run: |
          echo "Construyendo imágenes Docker..."
          while IFS== read -r dir image; do
            if [ -d "./$dir" ]; then
              echo "Construyendo imagen para $dir..."
              docker build -t "$DOCKER_USERNAME/$image:latest" "./$dir" || echo "ERROR: Fallo al construir $dir."
            else
              echo "WARNING: Directorio $dir no encontrado. Omitiendo construcción para $dir."
            fi
          done <<< "$SERVICES"

      # Paso 6: Subir imágenes Docker
      - name: Push Docker Images
        run: |
          echo "Subiendo imágenes Docker..."
          while IFS== read -r dir image; do
            if docker images | grep -q "$image"; then
              echo "Subiendo imagen $DOCKER_USERNAME/$image:latest..."
              docker push "$DOCKER_USERNAME/$image:latest" || echo "ERROR: Fallo al subir $image."
            else
              echo "WARNING: Imagen $DOCKER_USERNAME/$image:latest no encontrada. Omitiendo subida para $dir."
            fi
          done <<< "$SERVICES"

      # Paso 7: Actualizar despliegues en Kubernetes
      - name: Deploy to Kubernetes
        run: |
          echo "Actualizando despliegues en Kubernetes..."
          while IFS== read -r dir image; do
            echo "Actualizando despliegue para $image..."
            kubectl set image deployment/${image//dummy-/} $image=$DOCKER_USERNAME/$image:latest || echo "ERROR: Fallo al actualizar $image."
          done <<< "$SERVICES"
