name: Kubernetes Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Configure Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

      - name: Update Kubernetes Deployments
        run: |
          kubectl set image deployment/frontend-angular frontend-angular=${{ secrets.DOCKER_USERNAME }}/frontend-angular:latest
          kubectl set image deployment/backend-express backend-express=${{ secrets.DOCKER_USERNAME }}/backend-express:latest
          kubectl set image deployment/backend-flask backend-flask=${{ secrets.DOCKER_USERNAME }}/backend-flask:latest
